### ISSUE TITLE
Update on the osm-seed web base image

### ISSUE THREAD

**Issue by Rub21** [osm-sandbox/osm-sandbox-deploy#3]
A week ago, we were using the images we deployed here, but the cgimap process in that image was not working properly. As a result, large data uploads/downloads may take time in the app. We have updated cgimap to version 2.1 in a new osm-seed base image, which can be used to improve performance when uploading and downloading data.

- docker image `developmentseed/osmseed-web:1.0.0-dev.h686c7c0`
- Helm version https://devseed.com/osm-seed-chart/osm-seed-1.0.0-dev.h686c7c0.tgz

cc. @quincylvania

**Comment by quincylvania** [comment]
@Rub21 Thanks!! I was running into the slow data uploads issue but didn't realize it was caused by this.
